services:
  - type: web
    name: kontrib
    runtime: node
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
